# application.yml
orbien:
  client:
    enabled: false
    server-addr: 127.0.0.1
    auth:
      token: CC67B56E53A065AC37EBF1CA65E9493B
    proxy:
      protocol: https
      tls:
        cert-file: classpath:cert/server.crt
        key-file: classpath:cert/server.key
    #  remote-port: 8787