version: "3.8"

services:
  etps-mysql:
    image: mysql:8.4
    container_name: etps-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: etps.123456
      MYSQL_DATABASE: etps
    networks:
      - etps-net
    volumes:
      - /opt/etps/mysql/data:/var/lib/mysql

  etps:
    image: xiaoniucode/etps:latest
    container_name: etps
    restart: unless-stopped
    ports:
      - "8020:8020"
      - "9527:9527"
      - "8600-8609:8600-8609"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=512m -XX:+UseG1GC"
    volumes:
      - /opt/etps/config:/app/config
      - /opt/etps/certs:/app/certs
      - /opt/etps/logs:/app/logs
    networks:
      - etps-net
    depends_on:
      - etps-mysql

networks:
  etps-net:
    driver: bridge