server_addr = "localhost"
server_port = 9527

[auth]
token = "5E793FAD27AA713D"

[connection]
[connection.retry]
initial_delay = 2
max_delay = 8
max_retries = 5

# 预创建连接池
[connection.pool]
enabled = false

[connection.pool.multiplex]
plain = true
encrypt = true

[connection.pool.direct]
plain_count = 1
encrypt_count = 2

[transport]
[transport.multiplex]
enabled = true

[transport.tls]
enabled = true
cert_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/client.crt"
key_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/client.key"
ca_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/ca.crt"

#[[proxies]]
#name = "web1"
#protocol = "http"
#auto_domain = false
#custom_domains = ["a.domain1.com"]
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[[proxies]]
#name = "web11"
#protocol = "http"
#auto_domain = true
#sub_domains = ["a", "b"]
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[proxies.basic_auth]
#enabled = true
#users = [
#    { user = "user1", pass = "pass1" },
#    { user = "user2", pass = "pass2" }
#]
#[proxies.access_control]
#enabled = true
#mode = "allow"
#allow = ["43.135.115.160/32"]
#deny = []
#
#[[proxies]]
#name = "fullstack2"
#protocol = "http"
#custom_domains = ["etpp.domain2.com"]
#enabled = true
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#
#[proxies.load_balance]
#strategy = "random" # 负载均衡策略 roundrobin/weight/random/leastconn
#[proxies.health_check]
#enabled = true
#interval = 5 #检查间隔
#timeout = 2 #连接超时
#max_fail = 3
#path="/health" #健康检查路径(HTTP协议)
#
#[proxies.transport]
#multiplex = false
#compress = false
#encrypt = true
#
#[proxies.access_control]
#enabled = true
#mode = "allow"
#allow = ["43.135.115.160/32"]
#deny = []
#
#[proxies.bandwidth]
#enabled= true
#limit = "20M" #总带宽限制(可选) 20Mbps
#limit_in = "2M" #入口带宽限制(可选)
#limit_out = "2M" #出口带宽限制(可选)
#
#[[proxies]]
#name = "web2"
#protocol = "http"
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#custom_domains = ["etp.domain2.com"]
#[proxies.access_control]
#enabled = true
#mode = "allow"
#allow = ["127.0.0.1"]
#[proxies.basic_auth]
#enabled = true
#users = [
#    { user = "user1", pass = "123" },
#    { user = "user2", pass = "456" }
#]
[[proxies]]
name = "web22"
protocol = "http"
custom_domains = ["etp11.domain2.com"]
targets = [
    { host = "127.0.0.1", port = 3006, weight = 70, name = "web-instance-1" }
    #    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
]
#[proxies.bandwidth] #带宽限制
#limit = "20M" #总带宽限制(可选)
#limit_in = "2M" #入口带宽限制(可选)
#limit_out = "2M" #出口带宽限制(可选)
[proxies.transport]
multiplex = true
compress = true
encrypt = false
#[[proxies]]
#name = "mysql"
#protocol = "tcp"
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[proxies.access_control] #访问控制
#enabled = true
#mode = "allow"
#allow = ["127.0.0.1"]
#deny = []
[[proxies]]
name = "mysql2"
protocol = "tcp"
status = 1
remote_port = 3309
targets = [
    { host = "127.0.0.1", port = 3306, weight = 70, name = "mysql-instance-1" },
    { host = "127.0.0.1", port = 3306, weight = 90, name = "mysql-instance-2" }
]
[proxies.transport]
multiplex = true
compress = false
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn

[proxies.bandwidth] #带宽限制
limit = "2M" #总带宽限制(可选)
#limit_in = "64k" #入口带宽限制(可选)
#limit_out = "64k" #出口带宽限制(可选)

[[proxies]]
name = "redis"
protocol = "tcp"
status = 1
targets = [
    { host = "10.1.1.2", port = 6379, weight = 70, name = "redis-1" },
    { host = "10.1.1.1", port = 6379, weight = 30, name = "redis-2" }
]

[proxies.loadbalance]
strategy = "random" # 策略：roundrobin/weight/random/leastconn

[[proxies]]
name = "postgre"
protocol = "tcp"
remote_port = 5432
enabled = true
targets = [
    { host = "127.0.0.1", port = 5432, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 5432, weight = 30, name = "web-instance-2" }
]
[[proxies]]
name = "test"
protocol = "tcp"
enabled = true
remote_port = 5202
targets = [
    #    { host = "127.0.0.1", port = 8032, weight = 70, name = "test-instance-1" },
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = false
compress = false
encrypt = true
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn
[proxies.bandwidth] #带宽限制
limit = "2M" #总带宽限制(可选)
#limit_in = "10M" #入口带宽限制(可选)
#limit_out = "10M" #出口带宽限制(可选)


[[proxies]]
name = "test_mux"
protocol = "tcp"
enabled = true
remote_port = 5203
targets = [
    #    { host = "127.0.0.1", port = 8032, weight = 70, name = "test-instance-1" },
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = true
compress = false
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn
[proxies.bandwidth] #带宽限制
limit = "1M" #总带宽限制(可选)
#limit_in = "10M" #入口带宽限制(可选)
#limit_out = "10M" #出口带宽限制(可选)

[[proxies]]
name = "test_mux_tls"
protocol = "tcp"
enabled = true
remote_port = 5204
targets = [
    #    { host = "127.0.0.1", port = 8032, weight = 70, name = "test-instance-1" },
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = true
compress = false
encrypt = true
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn
[proxies.bandwidth] #带宽限制
limit = "2M" #总带宽限制(可选)
#limit_in = "10M" #入口带宽限制(可选)
#limit_out = "10M" #出口带宽限制(可选)

#文件日志
[log]
level = "info"
path = "log"
name = "etpc.log"
archive_pattern = "etpc.%d{yyyy-MM-dd}.log"
log_pattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
max_history = 30
total_size_cap = "1GB"
## 控制台日志
#[log.console]
#level = "info"
#log_pattern = "%d{HH:mm:ss} %msg%n"