serverAddr = "localhost"
serverPort = 9527
#认证
[auth]
token = "5E793FAD27AA713D"
[auth.retry]
initialDelay = 2
maxDelay = 8
maxRetries = 5

[mux]
enable = true #全局开启，可覆盖

[tls]
enable = false
certFile = "cert/openssl/client.crt"
keyFile = "cert/openssl/client.key"
caFile = "cert/openssl/ca.crt"

#[[proxies]]
#name = "web1"
#protocol = "http"
#autoDomain = false
#customDomains = ["a.domain1.com"]
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[[proxies]]
#name = "web11"
#protocol = "http"
#autoDomain = true
#subDomains = ["a", "b"]
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[proxies.basic_auth]
#enable = true
#users = [
#    { user = "user1", pass = "pass1" },
#    { user = "user2", pass = "pass2" }
#]
#[proxies.access_control]
#enable = true
#mode = "allow"
#allow = ["43.135.115.160/32"]
#deny = []
#
#[[proxies]]
#name = "fullstack2"
#protocol = "http"
#customDomains = ["etpp.domain2.com"]
#enable = true
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#
#[proxies.load_balance]
#strategy = "random" # 负载均衡策略 roundrobin/weight/random/leastconn
#[proxies.health_check]
#enable = true
#interval = 5 #检查间隔
#timeout = 2 #连接超时
#maxFail = 3
#path="/health" #健康检查路径(HTTP协议)
#
#[proxies.transport]
#mux = false
#compress = false
#encrypt = true
#
#[proxies.access_control]
#enable = true
#mode = "allow"
#allow = ["43.135.115.160/32"]
#deny = []
#
#[proxies.bandwidth]
#enable= true
#limit = "20M" #总带宽限制(可选) 20Mbps
#limitIn = "2M" #入口带宽限制(可选)
#limitOut = "2M" #出口带宽限制(可选)
#
#[[proxies]]
#name = "web2"
#protocol = "http"
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#customDomains = ["etp.domain2.com"]
#[proxies.access_control]
#enable = true
#mode = "allow"
#allow = ["127.0.0.1"]
#[proxies.basic_auth]
#enable = true
#users = [
#    { user = "user1", pass = "123" },
#    { user = "user2", pass = "456" }
#]
[[proxies]]
name = "web22"
protocol = "http"
customDomains = ["etp12.domain2.com"]
targets = [
    { host = "127.0.0.1", port = 3006, weight = 70, name = "web-instance-1" }
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
]
#[proxies.bandwidth] #带宽限制
#limit = "20M" #总带宽限制(可选)
#limitIn = "2M" #入口带宽限制(可选)
#limitOut = "2M" #出口带宽限制(可选)
[proxies.transport]
mux = true
compress = true
encrypt = false
#[[proxies]]
#name = "mysql"
#protocol = "tcp"
#status = 1
#targets = [
#    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
#    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-2" }
#]
#[proxies.access_control] #访问控制
#enable = true
#mode = "allow"
#allow = ["127.0.0.1"]
#deny = []
[[proxies]]
name = "mysql2"
protocol = "tcp"
status = 1
remotePort = 3309
targets = [
    { host = "127.0.0.1", port = 3306, weight = 70, name = "mysql-instance-1" },
    { host = "127.0.0.1", port = 3306, weight = 90, name = "mysql-instance-2" }
]
[proxies.transport]
mux = true
compress = false
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn

[proxies.bandwidth] #带宽限制
limit = "128k" #总带宽限制(可选)
limitIn = "64k" #入口带宽限制(可选)
limitOut = "64k" #出口带宽限制(可选)
[[proxies]]
name = "redis"
protocol = "tcp"
status = 1
targets = [
    { host = "10.1.1.2", port = 6379, weight = 70, name = "redis-1" },
    { host = "10.1.1.1", port = 6379, weight = 30, name = "redis-2" }
]

[proxies.loadbalance]
strategy = "random" # 策略：roundrobin/weight/random/leastconn

[[proxies]]
name = "postgre"
protocol = "tcp"
remotePort=5433
enable = true
targets = [
    { host = "127.0.0.1", port = 5432, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 5432, weight = 30, name = "web-instance-2" }
]

[[proxies]]
name = "test"
protocol = "tcp"
enable=true
remotePort = 5202
targets = [
#    { host = "127.0.0.1", port = 8032, weight = 70, name = "test-instance-1" },
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
mux = false
compress = false
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn
[proxies.bandwidth] #带宽限制
limit = "1M" #总带宽限制(可选)
#limitIn = "10M" #入口带宽限制(可选)
#limitOut = "10M" #出口带宽限制(可选)
[[proxies]]
name = "test_mux"
protocol = "tcp"
enable=true
remotePort = 5203
targets = [
#    { host = "127.0.0.1", port = 8032, weight = 70, name = "test-instance-1" },
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
mux = true
compress = true
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin" # 策略：roundrobin/weight/random/leastconn
[proxies.bandwidth] #带宽限制
limit = "100k" #总带宽限制(可选)
#limitIn = "10M" #入口带宽限制(可选)
#limitOut = "10M" #出口带宽限制(可选)

#日志
[log]
level = "debug"
path = "log"
name = "etpc.log"
archivePattern = "etpc.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"