server_addr = "localhost"
server_port = 9527

[auth]
token = "414083A8563774142CAC91DDB5C9A2ED"

##############################################################################################################
[connection]
[connection.retry]
initial_delay = 2
max_delay = 8
max_retries = 5

[connection.pool]
enabled = true

[connection.pool.multiplex]
plain = true
encrypt = true

[connection.pool.direct]
plain_count = 1
encrypt_count = 2

[transport]
[transport.multiplex]
enabled = true

[transport.tls]
enabled = true
cert_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/client.crt"
key_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/client.key"
ca_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/openssl/ca.crt"

##################################################代理配置############################################################
[[proxies]]
name = "web1"
protocol = "http"
custom_domains = ["a.domain1.com"]
status = 1
targets = [
    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 8091, weight = 30, name = "web-instance-2" },
    { host = "127.0.0.1", port = 8092, weight = 30, name = "web-instance-3" }
]
[[proxies]]
name = "web2"
protocol = "http"
sub_domains = ["web2sub1", "web2sub2"]
status = 1
targets = [
    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 8090, weight = 30, name = "web-instance-2" }
]
[proxies.basic_auth]
enabled = true
users = [
    { user = "user1", pass = "123" },
    { user = "user2", pass = "123" }
]
[proxies.access_control]
enabled = true
mode = "allow"
allow = ["43.135.115.160/32"]
deny = []

[[proxies]]
name = "web4"
protocol = "http"
auto_domain = true
targets = [
    { host = "127.0.0.1", port = 8084, weight = 70, name = "web4-instance-1" }
]

[proxies.load_balance]
strategy = "random"
[proxies.health_check]
enabled = true
interval = 5
timeout = 2
max_fail = 3
path="/health"

[proxies.transport]
multiplex = false
encrypt = true

[proxies.access_control]
enabled = true
mode = "allow"
allow = ["43.135.115.160/32"]
deny = []

[proxies.bandwidth]
enabled= true
limit = "4Mbps"
limit_in = "2Mbps"
limit_out = "2Mbps"

[[proxies]]
name = "web5"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 8090, weight = 30, name = "web-instance-2" }
]
custom_domains = ["web5.domain2.com"]
#[proxies.access_control]
#enabled = true
#mode = "allow"
#allow = ["127.0.0.1"]
[proxies.basic_auth]
enabled = true
users = [
    { user = "user", pass = "123" },
    { user = "user2", pass = "456" }
]
[[proxies]]
name = "web6"
protocol = "http"
custom_domains = ["web6.domain2.com"]
targets = [
    { host = "127.0.0.1", port = 3006, weight = 70, name = "web-instance-1" }
]
[proxies.bandwidth]
limit = "20Mbps"
[proxies.transport]
multiplex = true
encrypt = false
[[proxies]]
name = "mysql"
protocol = "tcp"
status = 1
targets = [
    { host = "127.0.0.1", port = 33061, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 33062, weight = 30, name = "web-instance-2" }
]
[proxies.access_control]
enabled = true
mode = "allow"
allow = ["127.0.0.1"]
deny = []
[[proxies]]
name = "ssh"
protocol = "tcp"
remote_port = 3309
targets = [
    { host = "127.0.0.1", port = 8022, weight = 1, name = "ssh" }
]
[proxies.transport]
multiplex = true
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin"

[proxies.bandwidth]
limit_in = "64Kbps"
limit_out = "64Kbps"

[[proxies]]
name = "redis"
protocol = "tcp"
status = 1
targets = [
    { host = "10.1.1.2", port = 6379, weight = 70, name = "redis-1" },
    { host = "10.1.1.1", port = 6379, weight = 30, name = "redis-2" }
]

[proxies.loadbalance]
strategy = "weight"

[[proxies]]
name = "PostgreSQL"
protocol = "tcp"
enabled = true
targets = [
    { host = "127.0.0.1", port = 5432, weight = 70, name = "web-instance-1" },
    { host = "127.0.0.1", port = 5432, weight = 30, name = "web-instance-2" }
]
[[proxies]]
name = "test"
protocol = "tcp"
enabled = true
targets = [
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = false
compress = false
encrypt = true
[proxies.loadbalance]
strategy = "leastconn"
[proxies.bandwidth]
limit_in = "2Mbps"

[[proxies]]
name = "test_mux"
protocol = "tcp"
enabled = true
targets = [
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = true
compress = false
encrypt = false
[proxies.loadbalance]
strategy = "roundrobin"
[proxies.bandwidth]
limit_total = "1Mbps"

[[proxies]]
name = "test_mux_tls"
protocol = "tcp"
enabled = true
targets = [
    { host = "127.0.0.1", port = 8032, weight = 90, name = "test-instance-2" }
]
[proxies.transport]
multiplex = true
compress = false
encrypt = true
[proxies.loadbalance]
strategy = "roundrobin"
[proxies.bandwidth]
limit_total = "20Mbps"

[[proxies]]
name = "test001"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test1" }
]

[[proxies]]
name = "test002"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test2" }
]

[[proxies]]
name = "test003"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test3" }
]

[[proxies]]
name = "test004"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test4" }
]

[[proxies]]
name = "test005"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test5" }
]

[[proxies]]
name = "test006"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test6" }
]

[[proxies]]
name = "test007"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test7" }
]

[[proxies]]
name = "test008"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test8" }
]

[[proxies]]
name = "test009"
protocol = "http"
targets = [
    { host = "127.0.0.1", port = 8090, weight = 1, name = "test9" }
]

[log]
level = "debug"
path = "log"
name = "etpc.log"
archive_pattern = "etpc.%d{yyyy-MM-dd}.log"
log_pattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
max_history = 30
total_size_cap = "1GB"
