server_addr = "0.0.0.0"
server_port = 9527
http_proxy_port = 80
https_proxy_port = 443
#root_domains = ["domain1.com", "domain2.com"]

########################################################################################################################
[[tokens]]
name="win"
token="token-value"
[[tokens]]
name="mac"
token="token-value"


[transport]
[transport.tls]
enabled = true
cert_file = "cert/transport/server.crt"
key_file = "cert/transport/server.key"
#ca_file = "cert/transport/ca.crt"
#
[transport.websocket]
enabled = true
server_port = 9528
path = "/tunnel"

[transport.quic]
enabled = true
server_port = 9529

[dashboard]
enabled = true
addr = "localhost"
port = 8020
username = "admin"
password = "123456"
#cert_file = "cert/transport/server.crt"
#key_file = "cert/transport/server.key"


