<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <groupId>io.github.lxien</groupId>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>orbien-main</artifactId>
    <version>0.26.0</version>
    <packaging>pom</packaging>
    <name>orbien-main</name>
    <properties>
        <lombok.version>1.18.42</lombok.version>
        <shade.mainClass>custom</shade.mainClass>
        <cyclonedx-maven-plugin.version>2.8.0</cyclonedx-maven-plugin.version>
    </properties>
    <modules>
        <module>orbien-client-app</module>
        <module>orbien-server-app</module>
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>${cyclonedx-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
