package io.github.lxien.orbien.client.identity;

import io.github.lxien.orbien.core.enums.AgentType;
import io.github.lxien.orbien.core.utils.StringUtils;
import io.netty.util.internal.logging.InternalLogger;
import io.netty.util.internal.logging.InternalLoggerFactory;
import lombok.Getter;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 * Agent 身份标识
 * <p>
 * 持久化路径 ~/.orbien/agent.id
 */
public final class AgentIdentity {

    private static final InternalLogger logger = InternalLoggerFactory.getInstance(AgentIdentity.class);
    private static final String FILE_NAME = "agent.id";
    private static final String KEY_IDENTITY = "agentId";

    @Getter
    private final String storagePath;
    private String currentIdentity;

    public AgentIdentity(AgentType agentType) {
        if (agentType != null && agentType.isStandalone()) {
            this.storagePath = getDefaultStoragePath();
            this.currentIdentity = loadFromStorage();
        } else {
            this.storagePath = null;
            this.currentIdentity = null;
        }
    }

    /**
     * 获取当前 Agent 身份标识
     *
     * @return 服务端下发的 agentId，如果本地不存在则返回 null
     */
    public String getIdentity() {
        return currentIdentity;
    }

    public boolean hasIdentity() {
        return StringUtils.hasText(currentIdentity);
    }

    public void updateIdentity(String identity) {
        updateIdentity(identity, storagePath != null);
    }

    /**
     * 更新身份标识
     */
    public void updateIdentity(String identity, boolean persist) {
        if (!StringUtils.hasText(identity)) {
            return;
        }

        this.currentIdentity = identity.trim();

        if (persist && storagePath != null) {
            persistToFile(this.currentIdentity);
        }
    }

    public void clearIdentity() {
        this.currentIdentity = null;
        if (storagePath == null) {
            return;
        }
        try {
            Files.deleteIfExists(Paths.get(storagePath));
        } catch (Exception e) {
            logger.warn("Failed to clear agent identity: {}", e.getMessage());
        }
    }

    private String loadFromStorage() {
        Path path = Paths.get(storagePath);
        if (!Files.exists(path)) {
            return null;
        }

        try (InputStream in = Files.newInputStream(path)) {
            Properties props = new Properties();
            props.load(in);
            return props.getProperty(KEY_IDENTITY);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * 持久化身份标识到本地文件
     */
    private void persistToFile(String identity) {
        try {
            Path path = Paths.get(storagePath);
            Files.createDirectories(path.getParent());

            Properties props = new Properties();
            props.setProperty(KEY_IDENTITY, identity);

            try (OutputStream out = new FileOutputStream(path.toFile())) {
                props.store(out, "orbien Agent Identity - Generated by server");
            }

            setOwnerOnlyPermissions(path);
        } catch (Exception e) {
            logger.warn("Failed to persist agent identity: {}", e.getMessage());
        }
    }

    private void setOwnerOnlyPermissions(Path path) {
        try {
            if (!System.getProperty("os.name").toLowerCase().contains("win")) {
                java.util.Set<java.nio.file.attribute.PosixFilePermission> perms = new java.util.HashSet<>();
                perms.add(java.nio.file.attribute.PosixFilePermission.OWNER_READ);
                perms.add(java.nio.file.attribute.PosixFilePermission.OWNER_WRITE);
                Files.setPosixFilePermissions(path, perms);
            }
        } catch (Exception ignored) {
            // 权限设置失败不影响功能
        }
    }

    private static String getDefaultStoragePath() {
        return Paths.get(System.getProperty("user.home"), ".orbien", FILE_NAME).toString();
    }
}
