package com.xiaoniucode.etp.client.manager;

import com.xiaoniucode.etp.common.utils.StringUtils;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 * Agent 身份标识
 * <p>
 * 负责管理服务端下发的 Agent 唯一标识。
 * - 二进制客户端：持久化到本地 ~/.etp/agent.id 文件
 */
public final class AgentIdentity {

    private static final String FILE_NAME = "agent.id";
    private static final String KEY_IDENTITY = "agentId";

    private final String storagePath;
    private String currentIdentity;

    public AgentIdentity() {
        this.storagePath = getDefaultStoragePath();
        this.currentIdentity = loadFromStorage();
    }

    /**
     * 获取当前 Agent 身份标识
     *
     * @return 服务端下发的 agentId，如果本地不存在则返回 null
     */
    public String getIdentity() {
        return currentIdentity;
    }
    public boolean hasIdentity(){
        return StringUtils.hasText(currentIdentity);
    }

    public void updateIdentity(String identity) {
        updateIdentity(identity, storagePath != null);
    }

    /**
     * 更新身份标识
     */
    public void updateIdentity(String identity, boolean persist) {
        if (identity == null || identity.isBlank()) {
            return;
        }

        this.currentIdentity = identity.trim();

        if (persist && storagePath != null) {
            persistToFile(this.currentIdentity);
        }
    }

    /**
     * 从本地文件加载身份标识
     */
    private String loadFromStorage() {
        File file = new File(storagePath);
        if (!file.exists()) {
            return null;
        }

        try (InputStream in = new FileInputStream(file)) {
            Properties props = new Properties();
            props.load(in);
            return props.getProperty(KEY_IDENTITY);
        } catch (Exception e) {
            System.err.println("[AgentIdentity] Failed to load agent identity: " + e.getMessage());
            return null;
        }
    }

    /**
     * 持久化身份标识到本地文件
     */
    private void persistToFile(String identity) {
        try {
            Path path = Paths.get(storagePath);
            Files.createDirectories(path.getParent());

            Properties props = new Properties();
            props.setProperty(KEY_IDENTITY, identity);

            try (OutputStream out = new FileOutputStream(path.toFile())) {
                props.store(out, "ETP Agent Identity - Generated by server");
            }

            // 非 Windows 系统设置文件权限（仅当前用户可读写）
            setOwnerOnlyPermissions(path);
        } catch (Exception e) {
            System.err.println("[AgentIdentity] Failed to persist agent identity: " + e.getMessage());
        }
    }

    private void setOwnerOnlyPermissions(Path path) {
        try {
            if (!System.getProperty("os.name").toLowerCase().contains("win")) {
                Files.setPosixFilePermissions(path,
                        java.util.Set.of(
                                java.nio.file.attribute.PosixFilePermission.OWNER_READ,
                                java.nio.file.attribute.PosixFilePermission.OWNER_WRITE
                        ));
            }
        } catch (Exception ignored) {
            // 权限设置失败不影响功能
        }
    }

    /**
     * 默认存储路径
     */
    private static String getDefaultStoragePath() {
        return Paths.get(System.getProperty("user.home"), ".etp", FILE_NAME).toString();
    }
}