// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TunnelMessage.proto
// Protobuf Java Version: 4.32.1

package cn.xilio.etp.core.protocol;

@com.google.protobuf.Generated
public final class TunnelMessage extends com.google.protobuf.GeneratedFile {
  private TunnelMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      TunnelMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.xilio.etp.core.protocol.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
     * @return The type.
     */
    cn.xilio.etp.core.protocol.TunnelMessage.Message.Type getType();

    /**
     * <code>int64 session_id = 2;</code>
     * @return The sessionId.
     */
    long getSessionId();

    /**
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>uint32 port = 4;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>string ext = 5;</code>
     * @return The ext.
     */
    java.lang.String getExt();
    /**
     * <code>string ext = 5;</code>
     * @return The bytes for ext.
     */
    com.google.protobuf.ByteString
        getExtBytes();
  }
  /**
   * Protobuf type {@code cn.xilio.etp.core.protocol.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cn.xilio.etp.core.protocol.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      ext_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.xilio.etp.core.protocol.TunnelMessage.internal_static_cn_xilio_etp_core_protocol_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.xilio.etp.core.protocol.TunnelMessage.internal_static_cn_xilio_etp_core_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.xilio.etp.core.protocol.TunnelMessage.Message.class, cn.xilio.etp.core.protocol.TunnelMessage.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.xilio.etp.core.protocol.Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTH = 0;</code>
       */
      AUTH(0),
      /**
       * <code>CONNECT = 1;</code>
       */
      CONNECT(1),
      /**
       * <code>DISCONNECT = 2;</code>
       */
      DISCONNECT(2),
      /**
       * <code>TRANSFER = 3;</code>
       */
      TRANSFER(3),
      /**
       * <code>HEARTBEAT = 4;</code>
       */
      HEARTBEAT(4),
      /**
       * <code>ERROR = 5;</code>
       */
      ERROR(5),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 32,
          /* patch= */ 1,
          /* suffix= */ "",
          Type.class.getName());
      }
      /**
       * <code>AUTH = 0;</code>
       */
      public static final int AUTH_VALUE = 0;
      /**
       * <code>CONNECT = 1;</code>
       */
      public static final int CONNECT_VALUE = 1;
      /**
       * <code>DISCONNECT = 2;</code>
       */
      public static final int DISCONNECT_VALUE = 2;
      /**
       * <code>TRANSFER = 3;</code>
       */
      public static final int TRANSFER_VALUE = 3;
      /**
       * <code>HEARTBEAT = 4;</code>
       */
      public static final int HEARTBEAT_VALUE = 4;
      /**
       * <code>ERROR = 5;</code>
       */
      public static final int ERROR_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return AUTH;
          case 1: return CONNECT;
          case 2: return DISCONNECT;
          case 3: return TRANSFER;
          case 4: return HEARTBEAT;
          case 5: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.xilio.etp.core.protocol.TunnelMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.xilio.etp.core.protocol.Message.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public cn.xilio.etp.core.protocol.TunnelMessage.Message.Type getType() {
      cn.xilio.etp.core.protocol.TunnelMessage.Message.Type result = cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.forNumber(type_);
      return result == null ? cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.UNRECOGNIZED : result;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private long sessionId_ = 0L;
    /**
     * <code>int64 session_id = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_ = 0;
    /**
     * <code>uint32 port = 4;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int EXT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ext_ = "";
    /**
     * <code>string ext = 5;</code>
     * @return The ext.
     */
    @java.lang.Override
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <code>string ext = 5;</code>
     * @return The bytes for ext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.AUTH.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(2, sessionId_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(3, payload_);
      }
      if (port_ != 0) {
        output.writeUInt32(4, port_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, ext_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.AUTH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sessionId_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, port_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, ext_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.xilio.etp.core.protocol.TunnelMessage.Message)) {
        return super.equals(obj);
      }
      cn.xilio.etp.core.protocol.TunnelMessage.Message other = (cn.xilio.etp.core.protocol.TunnelMessage.Message) obj;

      if (type_ != other.type_) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getExt()
          .equals(other.getExt())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.xilio.etp.core.protocol.TunnelMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.xilio.etp.core.protocol.TunnelMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.xilio.etp.core.protocol.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.xilio.etp.core.protocol.Message)
        cn.xilio.etp.core.protocol.TunnelMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.xilio.etp.core.protocol.TunnelMessage.internal_static_cn_xilio_etp_core_protocol_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.xilio.etp.core.protocol.TunnelMessage.internal_static_cn_xilio_etp_core_protocol_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.xilio.etp.core.protocol.TunnelMessage.Message.class, cn.xilio.etp.core.protocol.TunnelMessage.Message.Builder.class);
      }

      // Construct using cn.xilio.etp.core.protocol.TunnelMessage.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        sessionId_ = 0L;
        payload_ = com.google.protobuf.ByteString.EMPTY;
        port_ = 0;
        ext_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.xilio.etp.core.protocol.TunnelMessage.internal_static_cn_xilio_etp_core_protocol_Message_descriptor;
      }

      @java.lang.Override
      public cn.xilio.etp.core.protocol.TunnelMessage.Message getDefaultInstanceForType() {
        return cn.xilio.etp.core.protocol.TunnelMessage.Message.getDefaultInstance();
      }

      @java.lang.Override
      public cn.xilio.etp.core.protocol.TunnelMessage.Message build() {
        cn.xilio.etp.core.protocol.TunnelMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.xilio.etp.core.protocol.TunnelMessage.Message buildPartial() {
        cn.xilio.etp.core.protocol.TunnelMessage.Message result = new cn.xilio.etp.core.protocol.TunnelMessage.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.xilio.etp.core.protocol.TunnelMessage.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sessionId_ = sessionId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.port_ = port_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.ext_ = ext_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.xilio.etp.core.protocol.TunnelMessage.Message) {
          return mergeFrom((cn.xilio.etp.core.protocol.TunnelMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.xilio.etp.core.protocol.TunnelMessage.Message other) {
        if (other == cn.xilio.etp.core.protocol.TunnelMessage.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (!other.getPayload().isEmpty()) {
          setPayload(other.getPayload());
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                sessionId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                port_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                ext_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public cn.xilio.etp.core.protocol.TunnelMessage.Message.Type getType() {
        cn.xilio.etp.core.protocol.TunnelMessage.Message.Type result = cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.forNumber(type_);
        return result == null ? cn.xilio.etp.core.protocol.TunnelMessage.Message.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cn.xilio.etp.core.protocol.TunnelMessage.Message.Type value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.xilio.etp.core.protocol.Message.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 session_id = 2;</code>
       * @return The sessionId.
       */
      @java.lang.Override
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 session_id = 2;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(long value) {

        sessionId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 session_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 3;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 3;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>uint32 port = 4;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>uint32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {

        port_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ext_ = "";
      /**
       * <code>string ext = 5;</code>
       * @return The ext.
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ext = 5;</code>
       * @return The bytes for ext.
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ext = 5;</code>
       * @param value The ext to set.
       * @return This builder for chaining.
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ext_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string ext = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExt() {
        ext_ = getDefaultInstance().getExt();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string ext = 5;</code>
       * @param value The bytes for ext to set.
       * @return This builder for chaining.
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ext_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.xilio.etp.core.protocol.Message)
    }

    // @@protoc_insertion_point(class_scope:cn.xilio.etp.core.protocol.Message)
    private static final cn.xilio.etp.core.protocol.TunnelMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.xilio.etp.core.protocol.TunnelMessage.Message();
    }

    public static cn.xilio.etp.core.protocol.TunnelMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.xilio.etp.core.protocol.TunnelMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_xilio_etp_core_protocol_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_xilio_etp_core_protocol_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TunnelMessage.proto\022\032cn.xilio.etp.core" +
      ".protocol\"\330\001\n\007Message\0226\n\004type\030\001 \001(\0162(.cn" +
      ".xilio.etp.core.protocol.Message.Type\022\022\n" +
      "\nsession_id\030\002 \001(\003\022\017\n\007payload\030\003 \001(\014\022\014\n\004po" +
      "rt\030\004 \001(\r\022\013\n\003ext\030\005 \001(\t\"U\n\004Type\022\010\n\004AUTH\020\000\022" +
      "\013\n\007CONNECT\020\001\022\016\n\nDISCONNECT\020\002\022\014\n\010TRANSFER" +
      "\020\003\022\r\n\tHEARTBEAT\020\004\022\t\n\005ERROR\020\005B\017B\rTunnelMe" +
      "ssageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_xilio_etp_core_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_xilio_etp_core_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cn_xilio_etp_core_protocol_Message_descriptor,
        new java.lang.String[] { "Type", "SessionId", "Payload", "Port", "Ext", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
