//! 身份信息持久化路径：`~/.orbien/agent.id`
use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use tracing::{debug, warn};

const FILE_NAME: &str = "agent.id";
const KEY: &str = "agentId";

#[derive(Debug, Default)]
pub struct AgentIdentity {
    path: PathBuf,
    current: Option<String>,
}

impl AgentIdentity {
    pub fn load_default() -> Self {
        let path = default_path();
        let current = read_identity(&path);
        Self { path, current }
    }

    pub fn current(&self) -> Option<&str> {
        self.current.as_deref()
    }

    pub fn update(&mut self, agent_id: &str) {
        let id = agent_id.trim();
        if id.is_empty() {
            return;
        }
        self.current = Some(id.to_string());
        if let Err(e) = write_identity(&self.path, id) {
            warn!("持久化 agent.id 失败: {e}");
        } else {
            debug!("已更新 agent.id");
        }
    }

    pub fn clear(&mut self) {
        self.current = None;
        if self.path.exists() {
            if let Err(e) = fs::remove_file(&self.path) {
                warn!("清除 agent.id 失败: {e}");
            }
        }
    }
}

fn default_path() -> PathBuf {
    dirs_home()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".orbien")
        .join(FILE_NAME)
}

fn dirs_home() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
}

fn read_identity(path: &Path) -> Option<String> {
    let mut file = fs::File::open(path).ok()?;
    let mut text = String::new();
    file.read_to_string(&mut text).ok()?;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('!') {
            continue;
        }
        if let Some(rest) = line.strip_prefix(KEY) {
            let rest = rest.trim_start();
            if let Some(value) = rest.strip_prefix('=') {
                let value = value.trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
    }
    None
}

fn write_identity(path: &Path, agent_id: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut file = fs::File::create(path)?;
    writeln!(file, "#orbien Agent Identity - Generated by server")?;
    writeln!(file, "{KEY}={agent_id}")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(path, fs::Permissions::from_mode(0o600));
    }
    Ok(())
}
