server_addr = "127.0.0.1"
server_port = 9527

[auth]
token = "YOUR_TOKEN"

#[[proxies]]
#name = "MySQL"
#protocol = "tcp"
#local_ip = "127.0.0.1"
#local_port = 3306

#[[proxies]]
#name = "web"
#protocol = "http"
#local_ip = "127.0.0.1"
#local_port = 8080
#custom_domains = ["web.example.com"]
#auto_domain = true
