[package]
name = "orbien-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["lxien"]
description = "Orbien 客户端"
repository = "https://github.com/lxien/orbien"

[[bin]]
name = "orbien"
path = "src/main.rs"

[dependencies]
bytes = "1.10"
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1.45", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "signal"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2.2"
webpki-roots = "0.26"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
uuid = { version = "1.16", features = ["v4"] }
hostname = "0.4"
futures-util = { version = "0.3", features = ["sink"] }

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
bytes = "1.10"
