[target.arm-unknown-linux-musleabi]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabi:edge"

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:edge"

[target.riscv64gc-unknown-linux-musl]
image = "ghcr.io/cross-rs/riscv64gc-unknown-linux-musl:edge"

[target.loongarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-musl:edge"

[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:edge"

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:edge"
