spring:
  datasource:
    url: jdbc:h2:file:./etp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: false
logging:
  level:
    com.xiaoniucode.etp: debug
server:
  servlet:
    context-path: /

jwt:
  secret:
  expiration: 3600

security:
  permit-all:
    paths:
      - /
      - /static/**
      - /api/auth/login
      - /api/captcha
cache:
  caffeine:
    initial-capacity: 10000
    maximum-size: 150000
    expire-after-access: 30m
