spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: h2
logging:
  level:
    com.xiaoniucode.etp: debug
server:
  servlet:
    context-path: /

jwt:
  secret:
  expiration: 3600

security:
  permit-all:
    paths:
      - /api/auth/login
      - /api/captcha
cache:
  caffeine:
    initial-capacity: 10000
    maximum-size: 150000
    expire-after-access: 30m
