spring:
  profiles:
    active: mysql
server:
  servlet:
    context-path: /
jwt:
  secret:
  expiration: 3600
security:
  permit-all:
    paths:
      - /
      - /static/**
      - /api/auth/login
      - /api/captcha
cache:
  caffeine:
    initial-capacity: 10000
    maximum-size: 150000
    expire-after-access: 30m

logging:
  level:
    com.xiaoniucode.etp: debug