// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Status {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthInfo {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "AgentType", tag = "4")]
    pub agent_type: i32,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "6")]
    pub os: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub arch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateConnectionRequest {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateConnectionResponse {
    #[prost(string, tag = "1")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenStreamResponse {
    #[prost(uint32, tag = "1")]
    pub connection_id: u32,
    #[prost(string, tag = "2")]
    pub tunnel_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthResponse {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub connection_id: u32,
    #[prost(message, optional, tag = "3")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessControl {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(enumeration = "AccessMode", tag = "2")]
    pub mode: i32,
    #[prost(string, repeated, tag = "3")]
    pub allow: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub deny: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpUser {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasicAuth {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "2")]
    pub http_users: ::prost::alloc::vec::Vec<HttpUser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeaderRewriteRule {
    #[prost(enumeration = "HeaderDirection", tag = "1")]
    pub direction: i32,
    #[prost(enumeration = "HeaderAction", tag = "2")]
    pub action: i32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeaderRewrite {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<HeaderRewriteRule>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeAccessWindow {
    #[prost(string, tag = "1")]
    pub start: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub end: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeAccess {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(enumeration = "AccessMode", tag = "2")]
    pub mode: i32,
    #[prost(bool, tag = "3")]
    pub time_enabled: bool,
    #[prost(string, tag = "4")]
    pub timezone: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "5")]
    pub days: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "6")]
    pub windows: ::prost::alloc::vec::Vec<TimeAccessWindow>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Socks5User {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Socks5Auth {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "2")]
    pub users: ::prost::alloc::vec::Vec<Socks5User>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileShareUser {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub permission: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileShareAuth {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "2")]
    pub users: ::prost::alloc::vec::Vec<FileShareUser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileShareLimits {
    #[prost(string, tag = "1")]
    pub root_path: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub max_upload_size: i64,
    #[prost(bool, tag = "3")]
    pub allow_upload: bool,
    #[prost(bool, tag = "4")]
    pub allow_delete: bool,
    #[prost(bool, tag = "5")]
    pub allow_mkdir: bool,
    #[prost(bool, tag = "6")]
    pub allow_move: bool,
    #[prost(bool, tag = "7")]
    pub allow_rename: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileListRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sort: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub query: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub directory: bool,
    #[prost(int64, tag = "3")]
    pub size: i64,
    #[prost(int64, tag = "4")]
    pub modified_time: i64,
    #[prost(int64, tag = "5")]
    pub created_time: i64,
    #[prost(int64, tag = "6")]
    pub last_access_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileListResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub current_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub entries: ::prost::alloc::vec::Vec<FileEntry>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferInit {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub total_size: i64,
    #[prost(bool, tag = "5")]
    pub upload: bool,
    /// 下载时可选上限，0 表示不限制
    #[prost(int64, tag = "6")]
    pub max_bytes: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileChunk {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub offset: i64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub last: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferDone {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileOpRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub op: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileOpResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Target {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "4")]
    pub weight: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Domain {
    #[prost(bool, optional, tag = "1")]
    pub auto_domain: ::core::option::Option<bool>,
    #[prost(string, repeated, tag = "2")]
    pub custom_domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub sub_domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TlsCert {
    #[prost(string, tag = "1")]
    pub private_key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cert_chain_pem: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transport {
    #[prost(bool, optional, tag = "1")]
    pub multiplex: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "2")]
    pub encrypt: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub compress: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "4")]
    pub protocol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub compress_algorithm: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheck {
    #[prost(enumeration = "HealthCheckType", tag = "1")]
    pub r#type: i32,
    #[prost(int32, tag = "2")]
    pub interval: i32,
    #[prost(int32, tag = "3")]
    pub timeout: i32,
    #[prost(int32, tag = "4")]
    pub max_failed: i32,
    #[prost(string, tag = "5")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Proxy {
    #[prost(string, tag = "1")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ProtocolType", tag = "3")]
    pub protocol: i32,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "5")]
    pub targets: ::prost::alloc::vec::Vec<Target>,
    #[prost(bool, tag = "6")]
    pub force_https: bool,
    #[prost(uint32, optional, tag = "7")]
    pub remote_port: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "8")]
    pub domain: ::core::option::Option<Domain>,
    #[prost(message, optional, tag = "9")]
    pub access_control: ::core::option::Option<AccessControl>,
    #[prost(message, optional, tag = "10")]
    pub basic_auth: ::core::option::Option<BasicAuth>,
    #[prost(string, optional, tag = "11")]
    pub bandwidth: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "LoadBalanceStrategy", optional, tag = "12")]
    pub load_balance_strategy: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "13")]
    pub transport: ::core::option::Option<Transport>,
    #[prost(message, optional, tag = "14")]
    pub tls_cert: ::core::option::Option<TlsCert>,
    #[prost(message, optional, tag = "15")]
    pub health_check: ::core::option::Option<HealthCheck>,
    #[prost(message, optional, tag = "16")]
    pub socks5_auth: ::core::option::Option<Socks5Auth>,
    #[prost(message, optional, tag = "17")]
    pub file_auth: ::core::option::Option<FileShareAuth>,
    #[prost(message, optional, tag = "18")]
    pub file_limits: ::core::option::Option<FileShareLimits>,
    #[prost(message, optional, tag = "19")]
    pub header_rewrite: ::core::option::Option<HeaderRewrite>,
    #[prost(message, optional, tag = "20")]
    pub time_access: ::core::option::Option<TimeAccess>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeInfo {
    #[prost(string, tag = "1")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub targets: ::prost::alloc::vec::Vec<Target>,
    #[prost(string, repeated, tag = "4")]
    pub remote_addr: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub health_check: ::core::option::Option<HealthCheck>,
    #[prost(message, optional, tag = "6")]
    pub transport: ::core::option::Option<Transport>,
    #[prost(message, optional, tag = "7")]
    pub file_limits: ::core::option::Option<FileShareLimits>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCreateProxiesRequest {
    #[prost(message, repeated, tag = "1")]
    pub proxies: ::prost::alloc::vec::Vec<Proxy>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCreateProxiesResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<RuntimeInfo>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxySyncResponse {
    #[prost(enumeration = "ProxySyncType", tag = "1")]
    pub proxy_sync_type: i32,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<RuntimeInfo>,
    #[prost(string, repeated, tag = "3")]
    pub proxy_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceHealth {
    #[prost(string, tag = "1")]
    pub proxy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
    #[prost(enumeration = "HealthStatus", tag = "4")]
    pub status: i32,
    #[prost(uint64, tag = "5")]
    pub response_time_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchReportServiceHealthRequest {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ServiceHealth>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProtocolType {
    Tcp = 0,
    Http = 1,
    Https = 2,
    Udp = 3,
    Socks5 = 4,
    File = 5,
}
impl ProtocolType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Tcp => "TCP",
            Self::Http => "HTTP",
            Self::Https => "HTTPS",
            Self::Udp => "UDP",
            Self::Socks5 => "SOCKS5",
            Self::File => "FILE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TCP" => Some(Self::Tcp),
            "HTTP" => Some(Self::Http),
            "HTTPS" => Some(Self::Https),
            "UDP" => Some(Self::Udp),
            "SOCKS5" => Some(Self::Socks5),
            "FILE" => Some(Self::File),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentType {
    Binary = 0,
    Session = 1,
}
impl AgentType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Binary => "BINARY",
            Self::Session => "SESSION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BINARY" => Some(Self::Binary),
            "SESSION" => Some(Self::Session),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccessMode {
    Allow = 0,
    Deny = 1,
}
impl AccessMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Allow => "ALLOW",
            Self::Deny => "DENY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALLOW" => Some(Self::Allow),
            "DENY" => Some(Self::Deny),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoadBalanceStrategy {
    RoundRobin = 0,
    Weight = 1,
    Random = 2,
    LeastConn = 3,
}
impl LoadBalanceStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RoundRobin => "ROUND_ROBIN",
            Self::Weight => "WEIGHT",
            Self::Random => "RANDOM",
            Self::LeastConn => "LEAST_CONN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROUND_ROBIN" => Some(Self::RoundRobin),
            "WEIGHT" => Some(Self::Weight),
            "RANDOM" => Some(Self::Random),
            "LEAST_CONN" => Some(Self::LeastConn),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealthStatus {
    Unknown = 0,
    Up = 1,
    Down = 2,
}
impl HealthStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Up => "UP",
            Self::Down => "DOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "UP" => Some(Self::Up),
            "DOWN" => Some(Self::Down),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProxySyncType {
    Full = 0,
    Add = 1,
    Update = 2,
    Delete = 3,
}
impl ProxySyncType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Full => "FULL",
            Self::Add => "ADD",
            Self::Update => "UPDATE",
            Self::Delete => "DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FULL" => Some(Self::Full),
            "ADD" => Some(Self::Add),
            "UPDATE" => Some(Self::Update),
            "DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealthCheckType {
    Tcp = 0,
    Http = 1,
}
impl HealthCheckType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Tcp => "HEALTH_CHECK_TYPE_TCP",
            Self::Http => "HEALTH_CHECK_TYPE_HTTP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEALTH_CHECK_TYPE_TCP" => Some(Self::Tcp),
            "HEALTH_CHECK_TYPE_HTTP" => Some(Self::Http),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HeaderDirection {
    Unspecified = 0,
    Request = 1,
    Response = 2,
}
impl HeaderDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "HEADER_DIRECTION_UNSPECIFIED",
            Self::Request => "HEADER_DIRECTION_REQUEST",
            Self::Response => "HEADER_DIRECTION_RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEADER_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "HEADER_DIRECTION_REQUEST" => Some(Self::Request),
            "HEADER_DIRECTION_RESPONSE" => Some(Self::Response),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HeaderAction {
    Unspecified = 0,
    Set = 1,
    Add = 2,
    Remove = 3,
}
impl HeaderAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "HEADER_ACTION_UNSPECIFIED",
            Self::Set => "HEADER_ACTION_SET",
            Self::Add => "HEADER_ACTION_ADD",
            Self::Remove => "HEADER_ACTION_REMOVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEADER_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "HEADER_ACTION_SET" => Some(Self::Set),
            "HEADER_ACTION_ADD" => Some(Self::Add),
            "HEADER_ACTION_REMOVE" => Some(Self::Remove),
            _ => None,
        }
    }
}
