etp:
  client:
    enabled: true
    server-addr: 127.0.0.1
    server-port: 9527
    auth:
      token: 414083A8563774142CAC91DDB5C9A2ED
    proxy:
      custom-domains: gateway.domain1.com
      protocol: http
      transport:
        multiplex: true
        encrypt: true
    transport:
      tls:
        enabled: true
        cert-file: classpath:cert/client.crt
        key-file: classpath:cert/client.key
        ca-file: classpath:cert/ca.crt







