# application.yml
etp:
  client:
    enabled: true
    server-addr: 127.0.0.1
    auth:
      token: 414083A8563774142CAC91DDB5C9A2ED
    proxy:
      protocol: tcp
      sub-domains:
        - api
      bandwidth:
        limit-in: 1Mbps
        limit-out: 1Mbps
        limit-total: 2Mbps
#      basic-auth:
#        enabled: true
#        users:
#          - user: admin
#            pass: 123456
#          - user: guest
#            pass: 123456