etp:
  client:
    enabled: true
    server-addr: 127.0.0.1 # IP or domain
    auth:
      token: 5E793FAD27AA715D
#    proxy:
#      custom-domains: test.domain1.com
#      protocol: http
#      remote-port: 8008
    transport:
      tls:
        enabled: true
        cert-file: classpath:certs/client.crt
        key-file: classpath:certs/client.key
        ca-file: classpath:certs/ca.crt






