etp:
  client:
    enable: true
    server-addr: 127.0.0.1
    server-port: 9527
    auth:
      token: 5E793FAD27AA713D
      retry:
        initial-delay: 1
        max-delay: 20
        max-retries: 5
#
#    access-control:
#      enable: true
#      allow:
#        - localhost
#        - 192.168.0.1
#
#      mode: allow
#      deny:
#        - 127.0.0.1/32
#        - 127.0.0.3/34
#    bandwidth:
#      limit: 2M
#      limit-in: 1M
#      limit-out: 1M
#    basic-auth:
#      enable: true
#      users:
#        - user: admin
#          pass: 123
#        - user: guest
#          pass: 123
    proxy:
      protocol: tcp
      local-ip: 127.0.0.1
      auto-domain: true # http only
      custom-domains: # http only
        - example.com
        - test.com
      sub-domains: # http only
        - api
        - ui
#      remote-port: 8086 #tcp only
    transport:
      compress: true
      encrypt: false
      multiplex: true
    tls:
      enable: false
      cert-file: classpath:certs/client.crt
      key-file: classpath:certs/client.key
      ca-file: classpath:certs/ca.crt
      test-mode: false








